kind: EndpointSlice
metadata:
  name: electricsql-endpoint
addressType: IPv4
apiVersion: discovery.k8s.io/v1
endpoints:
  - addresses:
      -  #ELECTRICSQLIP
    conditions:
      ready: true
      serving: true
      terminating: false
ports:
  - name: http
    appProtocol: http
    port: 3000
---
kind: EndpointSlice
metadata:
addressType: IPv4
apiVersion: discovery.k8s.io/v1
endpoints:
  - addresses:
      -  #ELECTRICSQLFRONTENDIP
    conditions:
      ready: true
      serving: true
      terminating: false
ports:
  - name: http
    appProtocol: http
    port: 3000
