apiVersion: telemetry.datumapis.com/v1alpha1
kind: ExportPolicy
metadata:
  name: exportpolicy
spec:
  # Defines the telemetry sources that should be exported. An export policy can
  # define multiple telemetry sources. Telemetry data will **not** be de-duped
  # if its selected from multiple sources.
  sources:
    - name: "telemetry-metrics" # Descriptive name for the source
      # Source metrics from the Datum Cloud platform
      metrics:
        # The options in this section are expected to be mutually exclusive. Users
        # can either leverage metricsql or resource selectors.
        #
        # This option allows user to supply a metricsql query if they're already
        # familiar with using metricsql queries to select metric data from
        # Victoria Metrics.
        metricsql: |
          {service_name="telemetry.datumapis.com"}
    - name: "gateway-metrics" # Descriptive name for the source
      # Source metrics from the Datum Cloud platform
      metrics:
        # The options in this section are expected to be mutually exclusive. Users
        # can either leverage metricsql or resource selectors.
        #
        # This option allows user to supply a metricsql query if they're already
        # familiar with using metricsql queries to select metric data from
        # Victoria Metrics.
        metricsql: |
          {service_name="gateway.networking.k8s.io"}
  sinks:
    - name: grafana-cloud-metrics
      sources:
        - telemetry-metrics
        - gateway-metrics
      target:
        prometheusRemoteWrite:
          endpoint: #GRAFANA_CLOUD_ENDPOINT
          # The endpoint to send the telemetry data to. This should be a
          # Grafana Cloud endpoint.
          authentication:
            basicAuth:
              secretRef:
                name: "grafana-cloud-credentials"
          batch:
            timeout: 5s # Batch timeout before sending telemetry
            maxSize: 500 # Maximum number of telemetry entries per batch
          retry:
            maxAttempts: 3 # Maximum retry attempts
            backoffDuration: 2s # Delay between retry attempts
