apiVersion: v1
data:
  init.sql: |-
    CREATE TABLE scores (
      id SERIAL PRIMARY KEY,
      name VARCHAR(255),
      value FLOAT
    );
    INSERT INTO scores (name, value) VALUES
      ('Alice', 3.14),
      ('Bob', 2.71),
      ('Charlie', -1.618),
      ('David', 1.414),
      ('Eve', 0);
kind: ConfigMap
metadata:
  name: postgres-init-sql
  namespace: default
